# 

FILE_COMMENTS: dict[str, str] = {
    ".gitignore":           "Files to ignore in Git (e.g., __pycache__, .venv)",
    ".gitattributes":       "Git attribute settings",
    "README.md":            "Project description and setup instructions",
    "readme.md":            "Project description and setup instructions",
    "pyproject.toml":       "Build system and dependency config (modern alternative to setup.py)",
    "setup.py":             "Legacy package setup script",
    "setup.cfg":            "Package configuration",
    "requirements.txt":     "List of project dependencies",
    "requirements-dev.txt": "Dev/test-only dependencies",
    "requirements-test.txt":"Test-only dependencies",
    "Makefile":             "Common dev-task shortcuts (lint, test, build…)",
    "Dockerfile":           "Container image definition",
    "docker-compose.yml":   "Multi-container orchestration",
    ".env":                 "Environment variables — do NOT commit",
    ".env.example":         "Template showing required env vars",
    "package.json":         "Node.js dependencies and scripts",
    "tsconfig.json":        "TypeScript compiler configuration",
    ".eslintrc":            "ESLint linting rules",
    ".prettierrc":          "Prettier formatting rules",
    "vite.config.ts":       "Vite build configuration",
    "vite.config.js":       "Vite build configuration",
    "next.config.js":       "Next.js configuration",
    "webpack.config.js":    "Webpack bundler config",
    "__init__.py":          "Makes the directory a Python package",
    "main.py":              "Application entry point",
    "app.py":               "Application entry point",
    "index.py":             "Module index",
    "index.ts":             "Module index",
    "index.js":             "Module index",
    "utils.py":             "Shared utility / helper functions",
    "utils.ts":             "Shared utility / helper functions",
    "utils.js":             "Shared utility / helper functions",
    "helpers.py":           "Helper functions",
    "config.py":            "Configuration constants",
    "config.ts":            "Configuration constants",
    "settings.py":          "App settings and config",
    "models.py":            "Data models / ORM classes",
    "schemas.py":           "Validation schemas (e.g., Pydantic)",
    "routes.py":            "URL routing definitions",
    "views.py":             "View / controller logic",
    "serializers.py":       "Data serialization logic",
    "conftest.py":          "Shared pytest fixtures",
    "pytest.ini":           "Pytest configuration",
    "tox.ini":              "Tox test-runner configuration",
    ".pre-commit-config.yaml": "Pre-commit hook definitions",
    "LICENSE":              "Project license",
    "CHANGELOG.md":         "Version history and notable changes",
    "CONTRIBUTING.md":      "Guidelines for contributors",
}

DIR_COMMENTS: dict[str, str] = {
    "src":        "All importable source code lives here",
    "tests":      "Unit and integration tests",
    "test":       "Unit and integration tests",
    "docs":       "Project documentation",
    "scripts":    "Utility and automation scripts",
    "migrations": "Database migration files",
    ".github":    "GitHub Actions workflows and templates",
    "public":     "Publicly served static assets",
    "static":     "Static files (CSS, images, fonts…)",
    "assets":     "Static assets",
    "components": "UI components",
    "pages":      "Page-level components",
    "hooks":      "Custom React hooks",
    "store":      "State management (Redux, Zustand…)",
    "api":        "API route handlers",
    "lib":        "Shared internal library code",
    "utils":      "Utility functions",
    "config":     "Configuration files",
    "types":      "TypeScript type definitions",
}

# ── Defaults ───────────────────────────────────────────────────────────────────

DEFAULT_IGNORE: set[str] = {
    "__pycache__",
    ".venv",
    "venv",
    "env",
    ".env",
    ".git",
    ".hg",
    ".svn",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "*.egg-info",
    "dist",
    "build",
    "node_modules",
    ".DS_Store",
    "*.pyc",
    "*.pyo",
    ".idea",
    ".vscode",
    "*.iml",
}

